class ValidationError(Exception):
    """Raised when there are validation errors from Cerberus"""

    pass
